# Generated by Django 5.0.3 on 2024-03-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_rename_published_date_book_publication_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=20),
        ),
    ]
